---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  labels:
    function: hello
    example: serverless-lambda
  name: hello
spec:
  authenticationEnabled: false
  authentication:
    - type: JWT
      jwt:
        jwksUri: http://not-dex.kyma-system.svc.cluster.local:5556/keys
        issuer: https://not-dex.kyma.local
  hostname: hello.kyma.local
  service:
    name: hello
    port: 8080
