---
apiVersion: gateway.kyma.cx/v1alpha2
kind: Api
metadata:  
  labels:
    example: http-db-service
  name: http-db-service-2
  #namespace: kyma-system
spec:
  authentication:
  - type: JWT
    jwt:
      jwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys
      issuer: https://dex.kyma.local
  hostname: http-db-service-2.kyma.local
  service:
    name: http-db-service
    port: 8017
